# -------------------------------- #
#                                  #
#                SQL               #
#                                  #
# -------------------------------- #

host: "localhost"
port: "3306"
database: "zoriontp"
username: "root"
password: ""

# Only for experienced users
arguments: "?useSSL=false&allowPublicKeyRetrieval=true"

# -------------------------------- #
#                                  #
#             Operators            #
#                                  #
# -------------------------------- #
#
# These might seem confusing, but they aren't
# createBuy and createSell speak for themselves.
#
# On the other hand, buy and sell are a bit weird:
# First part of the declaration is from the seller's
# point of view, while the second half is from the
# buyer's point of view.

createBuy: "[buy]"
createSell: "[sell]"

# -------------------------------- #
#                                  #
#            Formatting            #
#                                  #
# -------------------------------- #
#
# Customize the formatting of the sign
# - Line 1: "&0{&c <Buy | Sell>&0 }"
# - Line 2: "&0<price> for x<amount>"
# - Line 3: "&n<item>"
# - Line 4: "&0<player>"
#
# Further you can also set some limits
# for the price and the amount.

signFormat:
  - "&0{&c {0}&0 }"
  - "&0{0} for x{1}"
  - "&n{0}"
  - "&0{0}"

maxPrice: 1000000
maxAmount: 64

# -------------------------------- #
#                                  #
#           Permissions            #
#                                  #
# -------------------------------- #
#
# Here you can set your own permission nodes,
# mind you that those will not be registered
# by permission plugins yet.

reloadPermission: "chestshop.admin.reload"
adminDeletePermission: "chestshop.admin.delete"

createBuyPermission: "chestshop.create.buy"
createSellPermission: "chestshop.create.sell"

deletePermission: "chestshop.delete"

# -------------------------------- #
#                                  #
#             Messages             #
#                                  #
# -------------------------------- #
#
# Customize the messages the way you want,
# includes normal color code support.

helpText:
  - "&7/chestshop&8 -&7 Brings up this menu."
  - "&7/chestshop reload&8 -&7 Reload the chestshop configuration."

noPermission: "&8&l[&c&li&8&l]&7 Sorry, but you do not have the permission to do this."
unknownCommand: "&8&l[&c&li&8&l]&7 Unknown command. Execute /chestshop to get a list of commands."
invalidArguments: "&8&l[&c&li&8&l]&7 It seems like the (amount of) given arguments are invalid."
shopCreated: "&8&l[&c&li&8&l]&7 Successfully created a new chestshop."
shopExists: "&8&l[&c&li&8&l]&7 This chest is already a chestshop."
shopRemoved: "&8&l[&c&li&8&l]&7 Successfully removed this chestshop."
shopOwnership: "&8&l[&c&li&8&l]&7 Sorry, but only shop owners or administrators can do this."
invalidItem: "&8&l[&c&li&8&l]&7 Sorry, but the chest does not contain a valid item."
invalidAmount: "&8&l[&c&li&8&l]&7 Sorry, but the amount you entered is invalid or too high."
invalidPrice: "&8&l[&c&li&8&l]&7 Sorry, but the price you entered is invalid or too high."
noHopper: "&8&l[&c&li&8&l]&7 Sorry, but you can't place a hopper below a chestshop."
reloadMessage: "&8&l[&c&li&8&l]&7 Successfully reloaded the chat configuration."