name: Chestshop
version: ${project.version}
main: eu.lukatjee.chestshop.chestShop
api-version: 1.16
authors: [ Lukatjee ]
description: Chestshop plugin
commands:
  chestshop:
    description: Main command
