name: Chestshop
version: 1.0-SNAPSHOT
main: eu.lukatjee.chestshop.chestShop
api-version: 1.16
authors: [ Lukatjee ]
description: Chestshop plugin
depend: [WildChests]
commands:
  chestshop:
    description: Main command
